apiVersion: v1
kind: Service
metadata:
  name: service-poke1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: update-demo-poke1
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.120.0.0/14
